# Generated by Django 4.0 on 2021-12-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armor', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='text',
        ),
    ]
